app/routes/docs.$lang.ts

* Add `docs/$lang.ts` file for redirection from `docs/:lang` to `docs/:lang/main`.

Fix #98: Redirect to main branch when only lang slug is present

---

app/styles/docsearch.css

As @ryuapp suggested I added `cursor: auto;` to the `DocSearch-Container` class.
Fixes #100

fix: docsearch modal hover cursor

---

app/root.tsx
app/ui/global-loading.tsx

According to @brophdawg11 's suggestion and issue #163 , I added this POC to the `root.tsx`.
In the example below I added a `await sleep(2000)` to the blog loaders and the theme switch action to see the complete animation and the places where the progressbar stops in both slow actions and loaders.
This was taken from my [blog post](https://dev.to/remix-run-br/creating-a-github-like-progress-bar-for-your-remix-app-153l) and I've been using this code successfully in almost all my Remix apps.
I appreciate any feedback if rejected and willing to make any modifications requested. ;)
I've chosen a gradient from `bg-blue-brand` to `bg-aqua-brand` I think works good on both dark and light modes.

feat: Add global loading indicator to top nav

---

app/routes/docs.$lang.$ref.tsx

While viewing the Remix documentation pages on my mobile device, I noticed the presence of an unnecessary scrollbar.
The mobile device I used for testing was a Galaxy Z Flip 3.
https://github.com/remix-run/remix-website/assets/66447334/7967254f-1175-45be-8e31-ba5683b0c178
I believe this issue emerged following the addition of a search icon to `<Header>` in this [PR](https://github.com/remix-run/remix-website/pull/177). So, I adjusted the gap between the logo and the list of icons within the `<Header>` to better accommodate mobile display sizes.
https://github.com/remix-run/remix-website/assets/66447334/1b85ac0a-8b7a-405b-9dc4-0e8a8f40fcf1
For reference, this unnecessary scrollbar was not observed on an iPhone SE. 
https://github.com/remix-run/remix-website/assets/66447334/33069091-a6ec-414 …

fix: remove unnecessary horizontal scrollbar

---

app/lib/md.server.ts
app/lib/mdtut.server.ts
package-lock.json
package.json

Fixes #155 
As mentioned by @brookslybrand , updating packages related to `remark` and `rehype` will result in several type errors.
In this PR, I updated the versions of the packages mentioned in this [issue](https://github.com/remix-run/remix-website/issues/155) to the latest versions and fixed the type errors that occurred.
Updating the following packages:
- rehype-autolink-headings
- rehype-slug
- rehype-stringify
- remark-gfm
- remark-html
- remark-parse
- remark-rehype
- unified
- unist-util-visit
The type errors mainly occurred within two files:
- **/app/lib/mdtut.server.ts**
- **/app/lib/md.server.ts**
Due to the removal of `CurrentTree` and the addition of `HeadTree` and `TailTree` to the [`Processor`'s type arguments](https://github.com/unifiedjs/unified/blob/b69689bba52a918d87aa6 …

Upgrade remark, rehype, and related packages and fix errors

---

app/root.tsx
app/routes/conf.2023.tsx
app/routes/docs.$lang.$ref.$.tsx
app/routes/docs.$lang.$ref.tsx

In this PR, I added zod validation for matches and remove `ts-expect-error` annotation.
- https://github.com/remix-run/remix-website/issues/109

Add types/validation for matches

---

app/routes/_extras.blog.rss[.xml].tsx
package-lock.json
package.json

closes #182 
As mentioned by @slorber and @brookslybrand , I also think that Remix should have an RSS feed for blog posts. Therefore, I updated it so that an appropriate RSS feed can be visible by accessing /blog/rss.xml.

feat: add /blog/rss.xml route

---

data/resources.yaml

http helmet allows for easily adding CSP and other security headers to your Remix or other application that uses web responses

chore(resources): add `@mcansh/http-helmet`

---

app/lib/blog.server.ts

Blog post authors are currently listed in alphabetical order. This change ensures that blog post authors are listed in the order they were defined in the post's frontmatter.

Allow custom blog post author order

---

app/lib/gh-docs/branches.ts
app/lib/gh-docs/docs.ts
app/lib/gh-docs/index.ts
app/lib/gh-docs/repo-content.ts
app/lib/gh-docs/tags.ts
app/lib/resources.server.ts
app/routes/$.tsx
app/routes/docs.$lang.$ref.$.tsx

mcansh/remix-fastify root README is a symlink to the README in packages/remix-fastify and using the raw.github... doesnt follow the redirect
closes #190
feel free to close if any of the other commenters on the issue also do the work so they can get the contribution :)
Signed-off-by: Logan McAnsh <logan@mcan.sh>

fix: resolve symlinked files

---

app/styles/docs.css

Balance spacing within multi-line alerts

---

app/styles/bailwind.css

While improving the styles to the site in #127 [this line was removed](https://github.com/remix-run/remix-website/commit/1692456460f9f06dc3b3c5e9ccf1175455dfd88b#diff-a77bf882aa4314d2c5c16abccc82037da094213a6f4d5b32d7ec907624227cc2L226-R223). This made all of the codeblocks on the docs look a little nicer.
However, it broke a bit of the home page experience toward the bottom:
Simply adding this style to the `__mutation_code` class fixed the problem.
Personally, I think removing as much from the remark/shiki parsing as we can is probably a good thing. In pretty much all other cases we selected the `pre` tag directly.
At some point I would really love to go through all the styling on the website and unify it a bit more, since right now there's not a completely cohesive look and feel. It's …

Add background color to __mutation_code class

---

app/lib/gh-docs/branches.ts
app/lib/gh-docs/docs.ts
app/lib/gh-docs/index.ts
app/lib/gh-docs/repo-content.ts
app/lib/gh-docs/tags.ts
app/lib/resources.server.ts
app/routes/$.tsx
app/routes/docs.$lang.$ref.$.tsx

In #191 we switched from using fetching against `https://raw.githubusercontent.com/` directly and instead opted to use `octokit`. While this was appropriate (and necessary) for the [resources](https://remix.run/resources) page, it caused a problem for our docs pages.
503 errors started showing up on the docs pages for various users
Inside of our Fly logs we started getting these errors
> Request quota exhausted for request GET /repos/{owner}/{repo}/contents/{path}
It seems like when trying to fetch the docs it would hit `octokit`'s rate limiting. I deployed this change to main ~45min before putting up this PR and so far errors seem to be abated
The only thing I'm still confused about is why this issue didn't show up sooner. Not sure if the amount of traffic we've been getting since [our …

fix: revert using octokit for getRepoContent

---

app/routes/docs.$lang.$ref.tsx

- Renders docs search bar on all branches by removing [these 2 lines](https://github.com/remix-run/remix-website/blob/main/app/routes/docs.%24lang.%24ref.tsx#L346-L347)
- Closes #200 
| Before | After |
| ------ | ----- |
| ![before](https://github.com/remix-run/remix-website/assets/40516784/a6523f08-7819-49bc-81da-c63968ffd09b) | ![after](https://github.com/remix-run/remix-website/assets/40516784/cff40d18-3eed-4a2e-b1ee-b4b65e8d89b2) |

Render docs search bar on all branches

---

app/routes/conf.2023._index.tsx
app/routes/conf.2023._inner.schedule.tsx
app/routes/conf.2023._inner.speakers.$speakerSlug.tsx
app/routes/conf.2023._inner.sponsor.tsx
app/routes/conf.2023.coc.tsx

I remove metaV1 from the routes whose url start with `/conf/2023/`
related https://github.com/remix-run/remix-website/issues/214

Remove @remix-run/v1-meta

---

app/lib/gh-docs/docs.ts
app/routes/docs.$lang.$ref.$.tsx

Adding some indentation for any headings less than h2 on the doc pages. Right now only h2s and h3s are allowed
@markdalgleish I think I mentioned this feature to you. If you have a second to give it a [quick sniff check](https://remixdotrunstage.fly.dev/docs/en/main/start/changelog) and make sure the indentation looks good I'd appreciate it :)

Add indenting for the side nav on docs sites

---

data/resources.yaml

This PR adds the [`remix-paraglidejs`](https://github.com/BRIKEV/remix-paraglidejs) library to the resources page. 
This is a remix library for working with the [ParaglideJS](https://inlang.com/m/gerre34r/library-inlang-paraglideJs) i18n library.

Add `remix-paraglidejs` to the Resources page

---

app/routes/docs.$lang.$ref.tsx
package-lock.json
package.json

This thing is pretty ridiculous
The way our docs works you can technically have a category menu be a page itself, in which case it needs to be a link.
Additionally that doc can have children, so it still needs to be a collapsable menu. This is a monstrosity, but no idea if we ever did this with previous releases, so need to give a decent default behavior.
I did my best to clean up the code and colocate css that should be the same.
Also, sorry for my juvenile test doc names
https://github.com/remix-run/remix-website/assets/12396812/4a442310-1720-4486-a17b-cf08830acefa

fix: account for menu categories that are also links

---

app/styles/tailwind.css

I updated the `tailwind.css` file to set `color-scheme` to `dark` when dark mode is enabled. This allows elements that do not have dark mode specific styles to fallback to the user-agent styles.
Below you will find a before and after image of the Remix docs loaded in the Brave browser. Focus your attention to the scrollbars, which are the only elements that I found to be impacted by this change.
Before:
After:
This is the same approach that the Tailwind CSS docs has taken: https://github.com/tailwindlabs/tailwindcss.com/blob/master/src/css/base.css
Kevin Powell has a great video that goes into more detail: https://www.youtube.com/watch?v=zFFuV_vXNhY

Set `color-scheme` to `dark` when dark mode is enabled

---

app/lib/conf2023.server.ts
app/lib/gh-docs/repo-content.ts
app/lib/resources.server/index.ts
vite.config.mts

[Undici does not garbage collect unconsumed response bodies](https://github.com/nodejs/undici?tab=readme-ov-file#garbage-collection)
> The [Fetch Standard](https://fetch.spec.whatwg.org/) allows users to skip consuming the response body by relying on [garbage collection](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management#garbage_collection) to release connection resources. Undici does not do the same. Therefore, it is important to always either consume or cancel the response body.
This ended up causing a memory leak because I was relying on this without realizing when determining whether or not a Remix Resource's creator has a GitHub Sponsors page setup.

Fix memory leaks with undici introduction

---

app/styles/docs.css

Fixes #260.
| Light mode | Dark mode before with annotation | Dark mode after |
|-|-|-|
| ![Light mode screenshot of the .client modules page in Remix documentation. There are no handdrawn arrows. The same texts corresponding to the texts in the dark mode screenshot are visually distinct.](https://github.com/remix-run/remix-website/assets/11722318/6fb4de20-c124-4f80-8398-ddba7da450d1) | ![Dark mode screenshot of the .client modules page in Remix documentation, with two handdrawn arrows, one pointing to "useEffect" and is labeled "link", another pointing to ".client" and is labeled "not a link". The two texts being pointed to otherwise appear identical in style.](https://github.com/remix-run/remix-website/assets/11722318/1a694599-f198-4974-b459-dc70f294ebec) | ![Dark mode screenshot of the …

fix: pre/code links in docs under dark mode now look like links

---

app/routes/docs.$lang.$ref.tsx

Currently switching branches or version throws users back to the index page.
I noticed that `VersionWarningMessage` preserves the path, so I just copied the logic over.

Make pathname stay when version changes in docs

---

app/routes/_extras.showcase.tsx

Currently the Showcase page is busted
https://github.com/remix-run/remix-website/assets/12396812/b8fb374e-2ec5-460c-8eb4-3637c9a7ea82
It seems to be a combination of too many examples and the autoplaying videos. I wanted to quickly fix page so we no longer have this experience, and will rework the page in #273

Fix busted showcase page on mobile

---

app/ui/subscribe.tsx

There is invisible text (i.e. text that is white, same as background) when showing a subscription confirmation.
The fix looks like this:

Fix invisible text

---

data/posts/fog-of-war.md

Draft PR to update our post to reflect the flag name change (https://github.com/remix-run/remix/pull/9763).
**TODO:**

Update blog post for new fog of war flag name

---

_redirects
data/posts/fog-of-war.md

The first link in [Matt's blogpost](https://remix.run/blog/fog-of-war) is [currently 404'ing](https://remix.run/docs/en/main/guides/fog-of-war). This PR:
- Updates the link to point to the ["Lazy Route Discovery" guide in the docs](https://remix.run/docs/en/main/guides/lazy-route-discovery)
- Adds a redirect from the `fog-of-war` URL to the `lazy-route-discovery` URL. I appended it to the bottom of the file, but perhaps it should be moved elsewhere? Or maybe not necessary at all? 🤷‍♂️

Fix URL: fog-of-war => lazy-route-discovery

---

app/routes/docs.$lang.$ref.tsx
data/posts/incremental-path-to-react-19.md
data/posts/merging-remix-and-react-router.md

Note: links all point to staging where you can see these changes in action
- Add banner to [latest version of Remix](https://remixdotrunstage.fly.dev/docs/en/main)
- Update ["Incremental Path to React 19: React Conf Follow-Up" blog post](https://remixdotrunstage.fly.dev/blog/incremental-path-to-react-19)
- Update ["Merging Remix and React Router" blog post](https://remixdotrunstage.fly.dev/blog/merging-remix-and-react-router)

Point docs and some blog posts to React Router v7

---

data/resources.yaml

This patch links these packages to the renamed GH org.

fix(data/resources): update `remix-client-cache` & `remix-toast` repo links

---

app/routes/jam/faq.tsx

When using the keyboard to navigate the FAQ toggles, no focus styles are shown except when the FAQ is expanded.

Add focus styles to the Remix Jam FAQ to improve accessibility

---

data/posts/react-router-and-react-server-components.md

This summary is much longer than surrounding posts now that it's not at the top, so this just tightens things up a bit.

Shorten RSC post summary
