- app/lib/gh-docs/docs.ts
- app/lib/gh-docs/index.ts
- app/routes/$.tsx
- app/routes/docs.$lang.$ref.$.tsx
probably a better alternative approach to this, but it works...
closes #165
Signed-off-by: Logan McAnsh <logan@mcan.sh>
> feat: query and render the changelog

- app/routes/docs.$lang.$ref.tsx
> fix: editUrl

- data/resources.yaml
@sergiodxa thanks for this library, it's so freaking helpful
> Switch featured Resource to Remix Utils

- data/resources.yaml
@mcansh/remix-fastify is a Fastify server request handler for Remix
> chore(resources): add `@mcansh/remix-fastify`

- app/root.tsx
- package-lock.json
- package.json
- vite.config.mts
- Upgrade to Remix v2.6.0
Close #168
> Upgrade to Remix v2.6.0

- app/routes/docs.$lang.$ref.tsx
Signed-off-by: Logan McAnsh <logan@mcan.sh>
> chore(VersionWarning): link to doc on main branch

- app/ui/homepage-scroll-experience.tsx
unsolicited PR to light up the konami code hotkeys as an easter egg
https://github.com/remix-run/remix-website/assets/5633704/0ace5fc0-a27d-4ffd-be33-4a10aa13db1a
> feature: make konami code interactive

- app/ui/homepage-scroll-experience.tsx
Leftover in https://github.com/remix-run/remix-website/pull/197
> Remove leftover console log

- data/posts/remix-heart-vite.md
- package-lock.json
- package.json
- vite.config.mts
upgrade packages.
Related #209
> upgrade packages

- app/routes/conf.2023._inner.schedule.tsx
- app/routes/conf.2023._inner.speakers.$speakerSlug.tsx
- app/routes/conf.2023._inner.sponsor.tsx
- app/routes/conf.2023.coc.tsx
In #215 I made a mistake about meta description, and so fix up.
> fix meta description

- data/posts/remix-heart-vite.md
Minor issue but it grabbed my attention while re-reading this post, it's _Cloudflare_ not _CloudFlare_.
> docs: fix casing Cloudflare

- app/routes/docs.$lang.$ref.tsx
Addresses https://github.com/remix-run/remix-website/issues/228
> Make Doc Sections Collapsable

- app/routes/docs.$lang.$ref.tsx
Improving the docs collapsable categories a bit
- Automatically open only current docs category -- resolves #234
> Docs Nav Scroll restoration

- app/env.server.ts
> fix missing ENV error message

- _redirects
This is in preparation for some changes made in [release-next](https://github.com/remix-run/remix/commit/2edd5114207e3b76033637fd8069c0f450059371)
> Add redirects for docs previously under "future"

- data/resources.yaml
Hello Brooks!
Came up with the updated `resources.yaml` discussed on Discord!
- Let me know if I should update/do anything else!
> Update resources - Remix SaaS

- app/routes/_marketing._index.tsx
- app/routes/docs.$lang.$ref.$.tsx
- app/routes/docs.$lang.$ref.tsx
- app/styles/bailwind.css
- app/styles/docs.css
- app/styles/index.css
- app/styles/md.css
- app/ui/buttons.tsx
- app/ui/fakebooks.tsx
- app/ui/homepage-scroll-experience.tsx
Fixes #148
Fixes a few other text color related issues I noticed while QA'ing
> Update text color contrast

- app/routes/_extras.showcase.tsx
Removing the video autoplay from mobile showcase. It's honestly a bit too noisy anyway imo
Fixes #273
> Remove mobile video code

- data/resources.yaml
> Feature Remix Auth

- app/routes/_extras.resources.$.tsx
Fixes resources with a slash in the name like https://remix.run/resources/@epic-web/remember
Will merge tomorrow in case something breaks
> Cleanup resource page params and meta tags

- md/marketing/mutations/mutations.md
> docs(mutations): Clarify where submission is coming from

- app/root.tsx
- app/routes/$.tsx
- app/routes/[_]actions.newsletter.tsx
- app/routes/_marketing._index.tsx
- app/routes/conf.2022._index.tsx
- app/routes/conf.2022._inner.speakers.$speakerSlug.tsx
- app/routes/conf.2023._index.tsx
- app/routes/conf.2023._inner.schedule.tsx
- app/routes/conf.2023._inner.speakers.$speakerSlug.tsx
- app/routes/conf.2023.tsx
- app/routes/docs.$lang.$ref.$.tsx
- package-lock.json
- package.json
- vite.config.ts
[staging site](https://remixdotrunstage.fly.dev/)
> Upgrade to Remix 2.13.0

- app/routes/docs.$lang.$ref.$.tsx
Added an active state to the side navigation heading based on user scroll.
> Add an active state to the side navigation

- app/routes/[_]actions.newsletter.tsx
- app/ui/subscribe.tsx
@brookslybrand fixed your type issues from the stream earlier
> Remove NewsletterActionData type

- app/routes/jam/faq.tsx
- app/routes/jam/storefront.server.ts
- app/routes/jam/utils.tsx
- Fix bug with local development where you needed the Shopify API
- Cleanup FAQ
- Add hotel block
> Minor improvements to Jam pages

- data/posts/react-router-and-react-server-components.md
This also affects the shared screenshot on X
> Fix example in RSC blog post
